app:
  scheduler:
    enable: true
    interval: 60000
    force-check-delay: 60000
  database-access-type: jdbc

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

api:
  github:
    base-url: https://api.github.com
    retryPolicy: linear
    retryNumber: 4
    statuses: INTERNAL_SERVER_ERROR,BAD_GATEWAY,INSUFFICIENT_STORAGE,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT
  stackoverflow:
    base-url: https://api.stackexchange.com/
    retryPolicy: linear
    retryNumber: 4
    statuses: INTERNAL_SERVER_ERROR,BAD_GATEWAY,INSUFFICIENT_STORAGE,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT
  bot:
    base-url: http://localhost:8090
    retryPolicy: linear
    retryNumber: 4
    statuses: INTERNAL_SERVER_ERROR,BAD_GATEWAY,INSUFFICIENT_STORAGE,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT

springdoc:
  swagger-ui:
    path: /swagger-ui
  bot:
    base-url: http://localhost:8090

hibernate:
  allow_update_outside_transaction: true

bucket:
  queryNumber: 10
