app:
  telegram-token: ${TOKEN}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

api:
  scrapper:
    base-url: http://localhost:8080
    retryPolicy: linear
    retryNumber: 4
    interval: 4
    statuses: INTERNAL_SERVER_ERROR,BAD_GATEWAY,INSUFFICIENT_STORAGE,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT

springdoc:
  swagger-ui:
    path: /swagger-ui

bucket:
  queryNumber: 10
